env:
  global:
    - CRATE_NAME=crc_complete

language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test --verbose
  - cargo test --verbose --no-default-features
  - cargo doc --no-deps

cache: cargo